---
- name: Converge
  hosts: powerdns
  become: true

  pre_tasks:
    - name: Install dig for testing
      ansible.builtin.apt:
        name: dnsutils
        state: present
        update_cache: true

  roles:
    - role: powerdns
