---
- name: Converge
  hosts: all
  become: true
  roles:
    - linux_base
  # To converge only a subset of linux_base, run molecule with tags, e.g.:
  #   molecule converge -s linux_base -- --tags timezone
