---
- name: Manage VLAN devices
  oxlorg.opnsense.interface_vlan:
    description: "{{ item.description }}"
    interface: "{{ item.interface | default(omit) }}"
    vlan: "{{ item.vlan | default(omit) }}"
    device: "{{ item.device | default(omit) }}"
    priority: "{{ item.priority | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    reload: true
  loop: "{{ opnsense_router_vlans }}"
  loop_control:
    label: "{{ item.description }}"

- name: Manage virtual IPs
  oxlorg.opnsense.interface_vip:
    address: "{{ item.address }}"
    interface: "{{ item.interface }}"
    mode: "{{ item.mode | default(omit) }}"
    gateway: "{{ item.gateway | default(omit) }}"
    description: "{{ item.description | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    reload: true
  loop: "{{ opnsense_router_vips }}"
  loop_control:
    label: "{{ item.address }} on {{ item.interface }}"
