---
- name: Set hostname using inventory_hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"

- name: Set fully qualified domain name in /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.1\.1\b'
    line: "127.0.1.1 {{ inventory_hostname }}.{{ local_zone_name }} {{ inventory_hostname }}"
    state: present
  when: local_zone_name is defined

- name: Remove cloud-init package
  ansible.builtin.package:
    name: cloud-init
    state: absent

- name: Make sure netplan is still present (dependency of cloud-init)
  ansible.builtin.package:
    name: netplan.io
    state: present
