- name: Install and configure dynamic dns client
  hosts: dyndns_clients
  become: yes
  tasks:
    - name: Update apt cache (from linux_base)
      include_role:
        name: linux_base
        tasks_from: 3_update-apt-cache

    - name: Configure dynamic dns client
      include_role:
        name: dyndns_client
