- name: Install k3s cluster
  hosts: k3s
  become: yes
  tasks:
    - name: Update apt cache (from linux_base)
      include_role:
        name: linux_base
        tasks_from: 3_update-apt-cache

    - name: Install k3s
      include_role:
        name: k3s
