---
- name: Create Pi-hole project directory
  ansible.builtin.file:
    path: "{{ pihole_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0750"

- name: Create Pi-hole persistent config directory
  ansible.builtin.file:
    path: "{{ pihole_dir }}/etc-pihole"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Render Pi-hole secrets env file
  ansible.builtin.template:
    src: pihole.env.j2
    dest: "{{ pihole_dir }}/.env"
    owner: root
    group: root
    mode: "0600"
  no_log: true

- name: Render Pi-hole compose file
  ansible.builtin.template:
    src: compose.yaml.j2
    dest: "{{ pihole_dir }}/compose.yaml"
    owner: root
    group: root
    mode: "0644"
